Allowing for co-existing Axon agents
Tripwire/chef-tripwire_agent pull request #11
Opened 2017-11-03 21:19 UTC by effective-spoons

== STORY / BUGS

Resolves #8
Resolves #9

== DETAILS

Enhancing the cookbook to allow users to set the service name for
the IP360 Axon agent as well as set its configuration directory
path.

Minor fixes to the custom resource to validate co-existing agents
can be installed by a wrapper cookbook.

== TESTING

kitchen test
foodctiric
cookstyle

2017-11-06 18:43 UTC, DavidWhitlock requested changes
I'll defer to someone else for approval.  I found a couple of  type-os, though.

2017-11-06 18:43 UTC, DavidWhitlock commented on .kitchen.yml
> +          install_directory: '/opt/tirpwire-ip360'
Type-o?  `tirpwire`

2017-11-06 18:43 UTC, DavidWhitlock commented on .kitchen.yml
> +          install_directory: '/opt/tirpwire-ip360'
Again, type-o?

2017-11-06 18:43 UTC, DavidWhitlock commented on CHANGELOG.md
> +Expanding axon's resources to support co-existing agents for TE, TLC, and IP360
I'm not sure if TLC is supported in this scenario yet.  You might want to double-check that.

2017-11-07 17:41 UTC, DavidWhitlock reviewed
Thank you for fixing those.

2017-11-10 21:33 UTC, DavidWhitlock approved these changes
Okay.  Let's get these changes merged in.

2017-11-10 21:33 UTC, hackalyze approved these changes

2017-11-10 21:36 UTC, DavidWhitlock approved these changes
Let's try this again.  I still approve.

2017-11-10 21:43 UTC, merged